name: Debug context

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ##############################################################################
  ##
  ## Debug job
  ##
  ##############################################################################

  Debug_Context:
    name: Debug received context
    runs-on: ubuntu-latest
    #runs-on: ["self-hosted", "m92p"]
    environment: ci_cd_pipeline

    steps:
      - name: Dump Github context
        run: |
          echo '${{ toJSON(github.event) }}'
